- name: vars
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  Tasks:
  - name: print the varaiable
    ansible.builtin.debug:
    msg: "Course is {{ COURSE }},Duration is {{DURATION}}, Trainer is {{TRAINER}} "