- name: variables
  hosts: local
  connection: local
  vars: #Play level variables, global variables
    COURSE: "Devops with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks:
  - name: print the varaiables
    vars: #Task level variables, accessible only with the task. Task variables can override play level variables.local variable
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }},Duration is {{DURATION}}, Trainer is {{TRAINER}}"

  - name: print the varaiables1
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }},Duration is {{DURATION}}, Trainer is {{TRAINER}}" 