- name: variables
  hosts: local
  connection: local
  vars: #Play level variables
    GREET: "PLAY"
  vars_files:
  - course.yaml  
  vars_prompt:
  - name: GREET
    prompt: Enter the value
    private: false
  tasks:
  - name: print the varaiable
    vars:
      GREET: "TASK"
    ansible.builtin.debug:
     msg: "Course is {{ COURSE }},Duration is {{DURATION}}, Trainer is {{TRAINER}}"


     #1 . Command line or args
     #2 . Task level