- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - { name: git , state: 'present'}
    - { name: mysql , state: 'absent'}
    - { name: gcc , state: 'present'}
    - { name: zip , state: 'absent'}